services:

  historie-service-mock:
    container_name: historie-service-mock
    image: ghcr.io/brp-api/historie-service-mock:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5010
    ports:
      - "5011:5010"
    networks:
      - brp-api-network

networks:
  brp-api-network:
    name: brp-api-network
