version: '3.4'

services:
  historieinformatieservice:
    container_name: historieinformatieservice
    image: ghcr.io/brp-api/historie-informatie-service:latest
    build:
      context: .
      dockerfile: Historie.Informatie.Service/Dockerfile

  historieservicemock:
    container_name: historieservicemock
    image: ghcr.io/brp-api/historie-service-mock:latest
    build:
      context: .
      dockerfile: Historie.Data.Mock/Dockerfile
